config/routes.rb
MenusV2::Application.routes.draw do
  devise_for :users

  get '/users/sign_in/' => 'devise/sessions#new', :as => 'sign_in'

  resources :menu_items

  resources :orders
  get '/orders/index/:email' => 'orders#index', :constraints => { :email=> /[^\/]*/ }
  get '/orders/view/:order_id' => 'orders#view', :as => 'view_order'
  get '/orders/submit/:id' => 'orders#submit', :as => 'submit_order'

  resources :line_items, :except => :show
  get '/line_items/new/:order_id' => 'line_items#new'
  get '/line_items/index' => 'line_items#index'
  get '/line_items/index/:order_id' => 'line_items#index'
  get '/line_items/:order_id'  => 'line_items#index'
  get '/line_items' => 'line_items#index'

  root :to => "line_items#index"

end

app/models/menu_item.rb
class MenuItem < ActiveRecord::Base
  attr_accessible :descr, :m_type, :meal, :name, :price
  has_many :line_items

  def self.get_line_items_menu_items_for_order(current_order)
    MenuItem.includes(:line_items).where("line_items.order_id = '#{current_order}'")
  end

  private

  def self.find_all_types
    MenuItem.select('distinct m_type').order('m_type ASC').map{|a| a.m_type }
  end

  def self.get_menu_items(m_type)
    m_type = 'Appetizers' if m_type.blank?
    MenuItem.find_all_by_m_type(m_type)
  end

end

app/controllers/menu_items_controller.rb
class MenuItemsController < ApplicationController
  # GET /menu_items
  # GET /menu_items.json
  before_filter :authenticate_user!

  def index
#   @menu_item = MenuItem.order("m_type")
#    if params[:m_type].blank?
#      m_type = 'Appetizers'
#    else
#      m_type = params[:m_type]
#    end
    @menu_item = MenuItem.find_all_by_m_type(params[:m_type])
    respond_to do |format|
      format.html # .html.erb
      format.json { render json: @menu_items }
    end
  end

  # GET /menu_items/1
  # GET /menu_items/1.json
  def show
    @menu_item = MenuItem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @menu_item }
    end
  end

  # GET /menu_items/new
  # GET /menu_items/new.json
  def new
    @menu_item = MenuItem.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @menu_item }
    end
  end

  # GET /menu_items/1/edit
  def edit
    @menu_item = MenuItem.find(params[:id])
  end

  # POST /menu_items
  # POST /menu_items.json
  def create
    @menu_item = MenuItem.new(params[:menu_item])

    respond_to do |format|
      if @menu_item.save
        format.html { redirect_to @menu_item, notice: 'Menu item was successfully created.' }
        format.json { render json: @menu_item, status: :created, location: @menu_item }
      else
        format.html { render action: "new" }
        format.json { render json: @menu_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /menu_items/1
  # PUT /menu_items/1.json
  def update
    @menu_item = MenuItem.find(params[:id])

    respond_to do |format|
      if @menu_item.update_attributes(params[:menu_item])
        format.html { redirect_to @menu_item, notice: 'Menu item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @menu_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menu_items/1
  # DELETE /menu_items/1.json
  def destroy
    @menu_item = MenuItem.find(params[:id])
    @menu_item.destroy

    respond_to do |format|
      format.html { redirect_to menu_items_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/menu_items_helper.rb
module MenuItemsHelper
end

app/views/menu_items/_form.html.erb
<%= form_for(@menu_item) do |f| %>
  <% if @menu_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@menu_item.errors.count, "error") %> prohibited this menu_item from being saved:</h2>

      <ul>
      <% @menu_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <b>Description</b><br />
    <%= f.text_field :descr %>
  </div>
  <div>
    <b>Name</b><br />
    <%= f.text_field :name %>
  </div>
  <div>
    <b>Price</b><br />
    <%= f.text_field :price %>
  </div>
  <div>
    <b>Menu Item Type</b><br />
    <%= f.text_field :m_type %>
  </div>
  <div>
    <b>Meal</b><br />
    <%= f.text_field :meal %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/menu_items/edit.html.erb
<div style="width: 350px; margin: auto;">
<h3>Modify Menu Items</h3>

<%= render 'form' %>

<%= link_to 'Show', @menu_item %> |
<%= link_to 'Back', menu_items_path %>
</div>

app/views/menu_items/index.html.erb
<div style="width: 500px; margin: auto;">
<h3>List of Menu Items</h3>
<%= flash[:notice] if flash[:notice] %>

<%= link_to 'New Menu item', new_menu_item_path %>
<table style="width:500px" border="1">
  <% @menu_item.each_with_index do |menu_item, i| %>
      <tr>
        <td style="width:400px"><b><%= menu_item.name %></b><br>
          <%= menu_item.descr %><br>
          <%= link_to 'Show', menu_item %>&nbsp;&nbsp;&nbsp;&nbsp;
          <%= link_to 'Edit', edit_menu_item_path(menu_item)%>&nbsp;&nbsp;&nbsp;&nbsp;
          <%= link_to 'Destroy', menu_item, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
        <td style="width:100px"><%= number_to_currency(menu_item.price) %></td>
      </tr>
  <% end %>
</table>
</div>

app/views/menu_items/new.html.erb
<div style="width: 350px; margin: auto;">
<h3>New Menu Item</h3>

<%= render 'form' %>

<%= link_to 'Back', menu_items_path %>
</div>

app/views/menu_items/show.html.erb
<div style="width: 500px; margin: auto;">
<p id="notice"><%= notice %></p>

<p>
  <b>Desc:</b>
  <%= @menu_item.descr %>
</p>

<p>
  <b>Name:</b>
  <%= @menu_item.name %>
</p>

<p>
  <b>Price:</b>
  <%= @menu_item.price %>
</p>

<p>
  <b>M type:</b>
  <%= @menu_item.m_type %>
</p>

<p>
  <b>Meal:</b>
  <%= @menu_item.meal %>
</p>


<%= link_to 'Edit', edit_menu_item_path(@menu_item) %> |
<%= link_to 'Back', menu_items_path %>
</div>