config/routes.rb
MenusV2::Application.routes.draw do
  devise_for :users

  get '/users/sign_in/' => 'devise/sessions#new', :as => 'sign_in'

  resources :menu_items

  resources :orders
  get '/orders/index/:email' => 'orders#index', :constraints => { :email=> /[^\/]*/ }
  get '/orders/view/:order_id' => 'orders#view', :as => 'view_order'
  get '/orders/submit/:id' => 'orders#submit', :as => 'submit_order'

  resources :line_items, :except => :show
  get '/line_items/new/:order_id' => 'line_items#new'
  get '/line_items/index' => 'line_items#index'
  get '/line_items/index/:order_id' => 'line_items#index'
  get '/line_items/:order_id'  => 'line_items#index'
  get '/line_items' => 'line_items#index'

  root :to => "line_items#index"

end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :line_items
  attr_accessible :address, :city, :email, :name, :order_id, :state, :status
  before_destroy :destroy_line_items

  def self.get_order(order_id)
    myorder = Order.find_by_order_id(order_id) if !order_id.nil?
    myorder
  end

  def self.set_order_id(params_order_id, current_order_id)
    if params_order_id
      order_id = params_order_id
    elsif current_order_id
      order_id = current_order_id
    end
    order_id
  end

  def self.submit_order(order_id)
    myorder = Order.get_order(order_id)
    myorder.status="Called In"
    myorder.save
    myorder
  end

  private

  def destroy_line_items
    @line_items = LineItem.find_all_by_order_id(self.order_id)
    @li_count = LineItem.find_all_by_order_id(self.order_id).count
    puts @line_items.inspect
    puts @li_count.inspect
    @line_items.each do |li|
      li.destroy
    end
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  before_filter :authenticate_user!, :only => [:submit, :show, :destroy, :index]

  # GET /orders
  # GET /orders.json
  def index

    #   redirect_to user_session_url if !user_signed_in?
    if current_user.role.to_s.eql?("admin")
      @orders = Order.all
    else
      @orders = Order.find_all_by_email(current_user.email)
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @orders }
    end
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    @order = Order.find_by_order_id(params[:order_id])
    if !@order.status.blank?
      redirect_to "/line_items/index/#{@order.order_id}"
    else
      redirect_to "/orders/view/#{@order.order_id}"
    end

#    respond_to do |format|
#      format.html # show.html.erb
#      format.json { render json: @order }
#    end
  end

  # GET /orders/new
  # GET /orders/new.json
  def new
    session[:return_to] = request.referer
    @order = Order.new
    @order.order_id = session[:order_id]
    @user = User.find_by_email(current_user.email) if !current_user.nil?

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @order }
    end
  end

  # GET /orders/1/edit
  def edit
    @order = Order.find(params[:id]) if !params[:id].nil?
#    @line_items = LineItem.find_all_by_order_id(@order.order_id)
#    redirect_to "/line_items/index/#{@order.order_id}"
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(params[:order])

    respond_to do |format|
      if @order.save
        #       format.html { redirect_to root_path(@order.order_id), notice: 'Order was successfully created.' }
        if !@order.status.eql?("")
          format.html { redirect_to "/line_items/index/#{@order.order_id}", notice: 'Order was successfully created.'}
        else
          format.html { redirect_to "/orders/view/#{@order.order_id}", notice: 'Order was successfully created.'}
        end
        format.json { render json: @menu_item, status: :created, location: @line_items }
      else
        format.html { render action: "new" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /orders/1
  # PUT /orders/1.json
  def update
    @order = Order.find(params[:id])
    respond_to do |format|
      if @order.update_attributes(params[:order])
#        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.html { redirect_to "/line_items/index/#{@order.order_id}", notice: 'Order was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order = Order.find(params[:id])
    session[:order_id] = nil
    @order.destroy

    respond_to do |format|
#      format.html { redirect_to orders_url }
      format.html { redirect_to request.referer }
      format.json { head :no_content }
    end
  end

  def submit

    # redirect_to new_user_session_url if !user_signed_in?
    @order = Order.submit_order(session[:order_id])
    #@order = Order.find_by_order_id(session[:order_id])
    #@order.status="Called In"
    #@order.save
    #@order = Order.get_order(session[:order_id])
    #OrderMailer.order_submitted_email(@order).deliver
    reset_session
#    session[:order_id] = nil

    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Order has been successfully submitted and will be processed.'   }
      format.json { head :no_content }
    end
  end

end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
    <% if @order.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

          <ul>
            <% @order.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <br>
    <div><b>Order ID:</b>&nbsp;<%= @order.order_id %></div>
    <div><b>Name:</b>&nbsp;<br />
      <%= f.text_field :name %>
    </div>
    <div><b>Address:</b>&nbsp;<br />
      <%= f.text_field :address %>
    </div>
    <div><b>Email:</b>&nbsp;<br />
      <%= f.text_field :email %>
    </div>
    <% if !@user.nil? and @user.role.to_s.eql?("admin") %>
        <div><b>Status:</b><br />
          <%= f.select :status, [ ' ', 'Called In', 'In Process', 'Completed' ] %>
        </div>
    <% end %>
    <%= f.hidden_field :order_id, :value => @order.order_id %><br>
    <%= f.submit "Complete Your Order" %>
<% end %>

app/views/orders/_your_order.html.erb
<br><br>
<table border="1" style="width:350px; background-color: white" cellpadding="6px" >
  <% if @order.nil? %>
      <% if !@mi_li.nil? %>
          <% if @mi_li.count > 0 %>
              <tr><td colspan="2">&nbsp;<%= link_to 'Complete Your Order',{:controller => "orders", :action => "new", :id => session[:order_id]} %></td></tr>
          <% end %>
      <% end %>
  <% else %>
      <% if !session[:order_id].nil? or !@order.blank? %>
          <tr><td colspan="2"><h4>Order Details</h4></td></tr>
          <tr>
            <td><b>Order ID:</b></td>
            <td><%= @order.order_id %></td>
          </tr>

          <tr>
            <td><b>Name:</b></td>
            <td><%= @order.name %></td>
          </tr>

          <tr>
            <td><b>Address:</b></td>
            <td><%= @order.address %></td>
          </tr>

          <tr>
            <td><b>Email:</b></td>
            <td><%= @order.email %></td>
          </tr>

          <tr>
            <td><b>Status:</b></td>
            <td><%= @order.status %></td>
          </tr>
          <% if @order.status.blank? %>
              <tr>
                <td colspan="2"><%= link_to "Edit Order Info", edit_order_path(@order) %></td>
              </tr>
              <tr>
                <td colspan="2"><%= link_to "Submit Order", submit_order_path(@order) %></td>
              </tr>
          <% end %>
      <% end %>
  <% end %>
</table>

app/views/orders/edit.html.erb
<div style="width: 350px; margin: auto;">
<h3>Update order</h3>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', request.referer %>
</div>

app/views/orders/index.html.erb
<div style="width: 900px; margin: auto;">
<table border="1" cellpadding=6px>
  <tr>
    <th>Order ID</th>
    <th>Name</th>
    <th>Address</th>
    <th>Email</th>
    <th>Status</th>
    <th>&nbsp;</th>
    <th>&nbsp;</th>
  </tr>

  <% @orders.each do |order| %>
      <% myorder = order.order_id %>
      <tr>
        <td><%= order.order_id %></td>
        <td><%= order.name %></td>
        <td><%= order.address %></td>
        <td><%= order.email %></td>
        <td><%= order.status %></td>
        <td><%= link_to 'View/Edit', "/line_items/index/#{myorder}" %></td>
        <td><%= link_to 'Remove', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>

      </tr>
  <% end %>
</table>
</div>

app/views/orders/new.html.erb
<div style="width: 200px; margin: auto;">
<h2>Complete Your Order</h2>

<%= render 'form' %>
<%= link_to 'Back', session[:return_to] %>
</div>