config/routes.rb
MenusV2::Application.routes.draw do
  devise_for :users

  get '/users/sign_in/' => 'devise/sessions#new', :as => 'sign_in'

  resources :menu_items

  resources :orders
  get '/orders/index/:email' => 'orders#index', :constraints => { :email=> /[^\/]*/ }
  get '/orders/view/:order_id' => 'orders#view', :as => 'view_order'
  get '/orders/submit/:id' => 'orders#submit', :as => 'submit_order'

  resources :line_items, :except => :show
  get '/line_items/new/:order_id' => 'line_items#new'
  get '/line_items/index' => 'line_items#index'
  get '/line_items/index/:order_id' => 'line_items#index'
  get '/line_items/:order_id'  => 'line_items#index'
  get '/line_items' => 'line_items#index'

  root :to => "line_items#index"

end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :menu_items

  attr_accessible :extras, :menu_item_id, :order_id, :spec_inst
  attr_accessor :m_type

end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  require 'securerandom'

  # GET /line_items
  # GET /line_items.json
  def index

    @menu_item = MenuItem.get_menu_items(params[:m_type])

    order_id = Order.set_order_id(params[:order_id], current_order)
    #if params[:order_id]
    #  order = params[:order_id]
    #elsif current_order
    #  order = current_order
    #end
    @order = Order.get_order(order_id)

#    if !current_order.blank?
    if !order_id.nil?
      @mi_li = MenuItem.get_line_items_menu_items_for_order(order_id)
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @menu_items }
    end
  end

  # GET /line_items/new
  # GET /line_items/new.json
  def new
    @menu_item = MenuItem.find(params[:id])
    @line_item = LineItem.new

    if session[:order_id].nil?
      session[:order_id] = SecureRandom.hex(7).upcase
    end

    session[:return_to] = request.referer

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @line_item }
    end
  end

  # GET /line_items/1/edit
  def edit
    # POST /line_items
    @line_item = LineItem.find(params[:id])
    @menu_item = MenuItem.find(@line_item.menu_item_id)

    session[:return_to] = request.referer

  end

  def create
    @line_item = LineItem.new(params[:line_item])
    respond_to do |format|
      if @line_item.save
        format.html { redirect_to session[:return_to], notice: 'Line item was successfully created.' }
#        format.html { redirect_to line_items_index_path, :m_type => params[:mtype], notice: 'Line item was successfully created.' }
#        format.html { redirect_to request.referer, notice: 'Line item was successfully created.' }
        format.json { render json: @menu_item, status: :created, location: @line_item }
      else
        format.html { render action: "new" }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /line_items/1
  # PUT /line_items/1.json
  def update
    @line_item = LineItem.find(params[:id])

    respond_to do |format|
      if @line_item.update_attributes(params[:line_item])
#        format.html { redirect_to line_items_index_path, :m_type => params[:m_type], notice: 'Line item was successfully updated.' }
        format.html { redirect_to session[:return_to], notice: 'Line item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.json
  def destroy
    @line_item = LineItem.find(params[:id])
    @line_item.destroy

    respond_to do |format|
      format.html { redirect_to line_items_url }
      format.json { head :no_content }
    end
  end

end

app/helpers/line_items_helper.rb
module LineItemsHelper
  @status = @order.status if !@order.nil?
end

app/views/line_items/_form.html.erb
<%= params[:m_type] %>
<%= form_for(@line_item) do |f| %>
  <% if @line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
      <% @line_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <br>
    <div><b>Item:&nbsp;</b><%= @menu_item.name %></div><br>

    <div><b>Desc:&nbsp;</b><%= @menu_item.descr %></div><br>

    <div><b>Price:&nbsp;</b><%= number_to_currency @menu_item.price %></div><br>
    <div><b>Order ID:&nbsp;</b><%= session[:order_id] %></div><br>
    <div><b>Special Instructions:&nbsp;</b><br />
    <%= f.text_area :spec_inst, :cols => 30, :rows => 5 %></div>
    <%= f.hidden_field :order_id, :value => session[:order_id] %><br>
    <%= f.hidden_field :menu_item_id, :value => @menu_item.id %>
    <%= f.submit "Add to Order" %>
<% end %>

app/views/line_items/_your_order.html.erb
<% @status = "no current order" if session[:order_id].nil? %>
<% if !@mi_li.blank? %>
    <table style="vertical-align: top; width: 350px; background-color: white" cellpadding="6px" border="1">
    <tr><td colspan="4"><h4>Items on your order:&nbsp;&nbsp;<%=current_order %></h4></td></tr>
<% end %>

<% @mytotal = 0 %>
<% if !@mi_li.blank? %>
    <% @mi_li.each_with_index do |mi_li, i| %>
        <% @mi_li[i].line_items.each do |li | %>
            <% @mytotal += mi_li.price %>
            <tr>
              <td> <%= mi_li.name %></td>
              <td><span style="float: right"> <%= number_to_currency(mi_li.price) %></span></td>
              <% if params[:controller].eql?("line_items") and @status.blank? %>
                  <td> <%= link_to 'Update', edit_line_item_path(li) %></td>
                  <td> <%= link_to 'Remove', li, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              <!--< else %>-->
                  <!--<td>&nbsp;</td>-->
                  <!--<td>&nbsp;</td>-->
              <% end %>
        <% end %>
    <% end %><br><br></tr>
    <tr><td><b>Sub Total:</b></td>
      <td><span style="float: right"><%= number_to_currency(@mytotal) %></span></td></tr>
    <tr><td><b>Tax:</b></td>
      <td><span style="float: right"><%= number_to_currency(@mytotal * 0.0825) %></span></td></tr>
    <tr><td>&nbsp;</td><td><hr></td></tr>
    <tr><td><b>Total (w/tax):</b></td>
      <td><span style="float: right"><%= number_to_currency(@mytotal * 1.0825) %></span></td></tr>

<% end %>
</table>

app/views/line_items/edit.html.erb
<div style="width: 350px; margin: auto;">
  <h3>Change your Order</h3>

  <%= render 'form' %>
<%= link_to 'Back', request.referer %>
</div>

app/views/line_items/index.html.erb
  <div class="span8">
    <% if !@menu_item.nil? %>
        <% @menu_item.each_with_index do |menu_item, i| %>
            <% if i%2 == 0
                  @bg = "background-color: lightgray;"
               else
                  @bg = "background-color: lavenderblush"
               end
            %>
            <div style="height: 65px;<%= @bg %>">
              <div style="margin-left: 10px; margin-right:10px">
              <span style="margin-top: 35px;"><b><%= link_to menu_item.name, new_line_item_path(:id => menu_item.id, :m_type => params[:m_type]) if @status.nil?%></b></span><span style="float: right"> <b><%= number_to_currency menu_item.price%></b></span><br>
              <%= menu_item.descr %>
              </div>
            </div>
        <% end %>
    <% end %>
  </div>
  <% if session[:order_id].nil? and @order.blank? %>
    <div class="span=3" style="vertical-align: top;">
  <% else %>
    <div class="span=3" style="border-style: solid; vertical-align: top; background-color: gray">
  <% end %>
        <%= render 'your_order'        %>
        <%= render 'orders/your_order' %>
    </div>

app/views/line_items/new.html.erb
<div style="width: 350px; margin: auto;">
  <h3>Add to Order</h3>

  <%= render 'form' %>
  <%= link_to 'Back', request.referer %>
</div>

app/views/line_items/show.html.erb
<%= form_for(@menu_item) do |f| %>
    <% if @menu_item.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@menu_item.errors.count, "error") %> prohibited this menu_item from being saved:</h2>

          <ul>
            <% @menu_item.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :name %><br />
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :descr %><br />
      <%= f.text_area :descr %>
    </div>
    <div class="field">
      <%= f.label :price %><br />
      <%= f.text_field :price %>
    </div>
    <div class="field">
      <%= f.label :m_type, "Type" %><br />
      <%= f.select :m_type, options_for_select([
                                                       ["Appetizers","Appetizers"],
                                                       ["Bagels","Bagels"],
                                                       ["Beverages","Beverages"],
                                                       ["Burgers","Burgers"],
                                                       ["Deserts","Deserts"],
                                                       ["Eggs","Eggs"],
                                                       ["Entrees", "Entrees"],
                                                       ["Fountain Sodas", "Fountain Sodas"],
                                                       ["Greek","Greek"],
                                                       ["Salads","Salads"],
                                                       ["Sandwiches","Sandwiches"],
                                                       ["Sides", "Sides"],
                                                       ["Smoothies and Juices","Smoothies and Juices"],
                                                       ["Pasta","Pasta"]
                                               ], @menu_item.m_type), :prompt => "Select a Type" %>
    </div>
    <div class="field">
      <%= f.label :meal %><br />
      <%= f.select :meal, options_for_select([["Breakfast", "Breakfast"],["Lunch", "Lunch"],["Dinner","Dinner"]], @menu_item.meal), :prompt => "Select a Meal" %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>