config/routes.rb
MenusV2::Application.routes.draw do
  devise_for :users

  get '/users/sign_in/' => 'devise/sessions#new', :as => 'sign_in'

  resources :menu_items

  resources :orders
  get '/orders/index/:email' => 'orders#index', :constraints => { :email=> /[^\/]*/ }
  get '/orders/view/:order_id' => 'orders#view', :as => 'view_order'
  get '/orders/submit/:id' => 'orders#submit', :as => 'submit_order'

  resources :line_items, :except => :show
  get '/line_items/new/:order_id' => 'line_items#new'
  get '/line_items/index' => 'line_items#index'
  get '/line_items/index/:order_id' => 'line_items#index'
  get '/line_items/:order_id'  => 'line_items#index'
  get '/line_items' => 'line_items#index'

  root :to => "line_items#index"

end

app/views/layouts/application.html.erb
<% set_stuff(params[:controller]) %>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Menus</title>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:300,400,600' rel='stylesheet' type='text/css'>
</head>
<body>
<div style="margin-left: 10px">
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="#"><%= @mydisplay %></a>
        <div class="nav-collapse">
          <% if params[:controller].eql?("orders") %>
            &nbsp;
          <% else %>
          <ul class="nav">
                <% @m_type_arr.each do |m| %>
                    <% if params[:controller].eql?("line_items") %>
                       <li> <%= link_to m, line_items_index_path(:m_type => m) %> </li>
                <% elsif params[:controller].eql?("menu_items") %>
                    <li> <%= link_to m, menu_items_path(:m_type => m) %> </li>
                <% end %>
            <% end %>
          </ul>
          <% end %>
        </div>
      </div>
      <div style="background-color: gray">
        <div style="margin-left: 110px">
          <% if user_signed_in? %>
              <%= current_user.email %> is logged in. &nbsp;&nbsp; Click Here to &nbsp;<%= link_to "Sign Out", destroy_user_session_path, :method => :delete, :style =>'color:red' %></li>
          <% else %>
              <% if !params[:controller].to_s[0..5].eql?("devise") %>
                  <%= link_to "Sign In", new_user_session_path, :style =>'color:red' %>
              <% end %>
          <% end %>
        </div>
      </div>
      <div style="background-color: darkslateblue">
        <div style="margin-left: 110px">
          <% if not @messages_rendered %>
              <% if flash[:error] %>
                  <p class='error'><%=h flash[:error] %></p>
              <% end  %>
              <% if flash[:notice] %>
                  <p class='notice'><%=h flash[:notice] %></p>
              <% else %>
                &nbsp;
              <% end %>
              <% @messages_rendered = true %>
          <% end %>
      </div>
    </div>
  </div>
</div>
</div>
<br><br><br><br>
<%= yield %>
</body>
</html>